# -*- coding: utf-8 -*-
"""TVxQ_EDA_Datathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhims1TVmAKqZ9V9TC0Pbt1WDto6cGug
"""

!pip install gdown

!gdown --folder https://drive.google.com/drive/folders/1lm5JrRj-v2KjwTnqalWWDggNer5Zkd8Y?usp=sharing

"""# **Phần 2: Trực quan hoá và Phân tích dữ liệu**

**1. Tại sao Revenue giảm dù traffic & signup tăng?:**

1.1 Traffic quality giảm
"""

# ===================== IMPORT =====================
import pandas as pd
import matplotlib.pyplot as plt

# ===================== ĐỌC DỮ LIỆU =====================
orders = pd.read_csv("Data/orders.csv")
web = pd.read_csv("Data/web_traffic.csv")

# ===================== XỬ LÝ DATETIME =====================
orders["order_date"] = pd.to_datetime(orders["order_date"])
web["date"] = pd.to_datetime(web["date"])

# ===================== FILTER ĐƠN HỢP LỆ =====================
orders_valid = orders[orders["order_status"] != "cancelled"]

# =========================================================
# 1. CR THEO THỜI GIAN (CONFIRM VẤN ĐỀ)
# =========================================================
orders_m = orders_valid.set_index("order_date").resample("ME")["order_id"].nunique()
sessions_m = web.set_index("date").resample("ME")["sessions"].sum()

cr = (orders_m / sessions_m).dropna()

plt.figure(figsize=(8,4))
plt.plot(cr)
plt.title("Conversion Rate Trend Over Time")
plt.xlabel("Time")
plt.ylabel("CR")
plt.show()

# =========================================================
# 2. CR THEO DEVICE (AI KÉO XUỐNG?)
# =========================================================
orders_device = orders_valid.groupby("device_type")["order_id"].count().reset_index()

# Không có sessions theo device → không tính CR chuẩn được
# → dùng tỷ trọng đơn hàng thay thế
total_orders = orders_device["order_id"].sum()
orders_device["share"] = orders_device["order_id"] / total_orders

print("\nOrders share by Device (proxy for CR):")
print(orders_device)

# =========================================================
# 3. CR THEO CHANNEL (TRAFFIC CÓ CHẤT LƯỢNG KHÔNG?)
# =========================================================
orders_channel = orders_valid.groupby("order_source")["order_id"].count().reset_index()
sessions_channel = web.groupby("traffic_source")["sessions"].sum().reset_index()

cr_channel = orders_channel.merge(
    sessions_channel,
    left_on="order_source",
    right_on="traffic_source"
)

cr_channel["cr"] = cr_channel["order_id"] / cr_channel["sessions"]

print("\nCR by Channel:")
print(cr_channel[["order_source", "cr"]])

# =========================================================
# 4. TRAFFIC vs ORDERS (CHECK QUALITY)
# =========================================================
plt.figure(figsize=(8,4))
plt.plot(sessions_m, label="Sessions")
plt.plot(orders_m, label="Orders (valid)")
plt.legend()
plt.title("Sessions vs Orders Over Time")
plt.xlabel("Time")
plt.ylabel("Count")
plt.show()

# =========================================================
# 5. TRAFFIC QUALITY THEO CHANNEL
# =========================================================
bounce_by_channel = web.groupby("traffic_source").apply(
    lambda x: (x["bounce_rate"] * x["sessions"]).sum() / x["sessions"].sum()
).reset_index(name="weighted_bounce")

print("\nBounce Rate by Channel (weighted):")
print(bounce_by_channel)

duration_by_channel = web.groupby("traffic_source")["avg_session_duration_sec"].mean().reset_index()
print("\nSession Duration by Channel:")
print(duration_by_channel)
# ===================== VẼ BIỂU ĐỒ =====================

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# --- Biểu đồ 1: Bounce rate ---
axes[0].bar(bounce_by_channel["traffic_source"], bounce_by_channel["weighted_bounce"])
axes[0].set_title("Bounce Rate theo Channel")
axes[0].set_xlabel("Traffic Source")
axes[0].set_ylabel("Bounce Rate")
axes[0].tick_params(axis='x', rotation=45)

# --- Biểu đồ 2: Session duration ---
axes[1].bar(duration_by_channel["traffic_source"], duration_by_channel["avg_session_duration_sec"])
axes[1].set_title("Session Duration theo Channel")
axes[1].set_xlabel("Traffic Source")
axes[1].set_ylabel("Avg Duration (sec)")
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# =========================================================
# 6. TRAFFIC QUALITY THEO THỜI GIAN
# =========================================================
web_m = web.set_index("date").resample("ME")[[
    "sessions",
    "bounce_rate",
    "avg_session_duration_sec"
]].mean()

plt.figure(figsize=(8,4))
plt.plot(web_m["bounce_rate"], label="Bounce Rate")
plt.plot(web_m["avg_session_duration_sec"], label="Session Duration")

plt.legend()
plt.title("Traffic Quality Over Time")
plt.xlabel("Time")
plt.ylabel("Value")
plt.show()

# =========================================================
# 7. (OPTIONAL) CANCEL RATE → CHECK DEVICE ISSUE
# =========================================================
cancel_rate_device = orders.groupby("device_type")["order_status"].apply(
    lambda x: (x == "cancelled").mean()
)

print("\nCancel Rate by Device:")
print(cancel_rate_device)

"""1.2 Funnel inefficiency

1.2.1 Payment completion (có drop không?)
"""

# ===================== PAYMENT SUCCESS RATE =====================
import pandas as pd

orders = pd.read_csv("Data/orders.csv")

# Định nghĩa đơn "thành công"
success_orders = orders[
    orders["order_status"]!= "cancelled"
]
success_rate = success_orders["order_id"].nunique() / orders["order_id"].nunique()

print("Order Success Rate:", success_rate)

"""1.2.2 Return rate theo channel (funnel hậu kỳ)"""

returns = pd.read_csv("Data/returns.csv")

returns_orders = returns.merge(orders, on="order_id")

return_by_channel = returns_orders.groupby("order_source")["order_id"].count() / orders.groupby("order_source")["order_id"].count()

print(return_by_channel)

import pandas as pd
import matplotlib.pyplot as plt

web = pd.read_csv("Data/web_traffic.csv")

web["date"] = pd.to_datetime(web["date"])
web["year"] = web["date"].dt.year

# Tổng sessions theo year + channel
channel_year = web.groupby(["year", "traffic_source"])["sessions"].sum().reset_index()

# Tính tỷ trọng %
channel_year["share"] = channel_year.groupby("year")["sessions"].transform(lambda x: x / x.sum())

print(channel_year.head())

# Pivot để plot
pivot = channel_year.pivot(index="year", columns="traffic_source", values="share")

pivot.plot(kind="line")
plt.title("Channel Mix Over Time")
plt.ylabel("Share of Traffic")
plt.show()

"""1.3 Giai đoạn chuyển đổi trước khi đặt hàng"""

shipments = pd.read_csv("Data/shipments.csv")
orders = pd.read_csv("Data/orders.csv")

shipments["ship_date"] = pd.to_datetime(shipments["ship_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

df = shipments.merge(orders, on="order_id")

shipping_trend = df.set_index("order_date").resample("ME")["shipping_fee"].mean()

plt.plot(shipping_trend); plt.title("Avg Shipping Fee Over Time"); plt.show()

import pandas as pd

order_items = pd.read_csv("Data/order_items.csv")
products = pd.read_csv("Data/products.csv")
orders = pd.read_csv("Data/orders.csv")

# ===================== LỌC ĐƠN HỢP LỆ =====================
valid_orders = orders[orders["order_status"] == "delivered"]

# ===================== MERGE =====================
df = order_items.merge(valid_orders[["order_id"]], on="order_id")
df = df.merge(products, on="product_id")

# ===================== REVENUE =====================
df["revenue"] = df["quantity"] * df["unit_price"]

portfolio = df.groupby("category").agg({
    "quantity": "sum",
    "revenue": "sum"
}).reset_index()

# ===================== AVERAGE PRICE =====================
portfolio["avg_price"] = portfolio["revenue"] / portfolio["quantity"]

print(portfolio)

import pandas as pd

# ===================== ĐỌC DỮ LIỆU =====================
order_items = pd.read_csv("Data/order_items.csv")
products = pd.read_csv("Data/products.csv")
orders = pd.read_csv("Data/orders.csv")

# ===================== LỌC ĐƠN HỢP LỆ =====================
# giữ tất cả đơn đã hoàn tất (không cancelled)
valid_orders = orders[orders["order_status"] != "cancelled"]

# tách riêng đơn RETURNED
returned_orders = orders[orders["order_status"] == "returned"]

# ===================== MERGE ORDER ITEMS =====================
df = order_items.merge(valid_orders[["order_id"]], on="order_id")
df = df.merge(products, on="product_id")

# ===================== FLAG RETURNED =====================
df["is_returned"] = df["order_id"].isin(returned_orders["order_id"]).astype(int)

# ===================== AGGREGATE THEO CATEGORY =====================
category_return = df.groupby("category").agg({
    "quantity": "sum",
    "is_returned": "sum"
}).reset_index()

# ===================== RETURN RATE =====================
category_return["return_rate"] = (
    category_return["is_returned"] / category_return["quantity"]
).fillna(0)

print(category_return)

"""**2. Tại sao AOV ↑ nhưng Revenue không tăng tương ứng?**

TH2: Số khách hàng giảm/mua ít hơn?
"""

import pandas as pd
import matplotlib.pyplot as plt

orders = pd.read_csv("Data/orders.csv")
orders["order_date"] = pd.to_datetime(orders["order_date"])

# số khách hàng mua mỗi tháng
customers_m = orders.groupby(pd.Grouper(key="order_date", freq="ME"))["customer_id"].nunique()

plt.plot(customers_m)
plt.title("Unique Customers Over Time")
plt.show()

inventory = pd.read_csv("Data/inventory.csv")

inventory["snapshot_date"] = pd.to_datetime(inventory["snapshot_date"])
inventory["year"] = inventory["snapshot_date"].dt.year

stockout_trend = inventory.groupby("year")["stockout_flag"].mean()

print(stockout_trend)

returns = pd.read_csv("Data/returns.csv")
orders = pd.read_csv("Data/orders.csv")

returns["return_date"] = pd.to_datetime(returns["return_date"])
returns["year"] = returns["return_date"].dt.year

return_trend = returns.groupby("year")["return_id"].count()

print(return_trend)

import pandas as pd
import matplotlib.pyplot as plt

# ===================== ĐỌC DỮ LIỆU =====================
orders = pd.read_csv("Data/orders.csv")
order_items = pd.read_csv("Data/order_items.csv")

# ===================== XỬ LÝ DATETIME =====================
orders["order_date"] = pd.to_datetime(orders["order_date"])

# ===================== SOLD PER YEAR =====================
order_items = order_items.merge(
    orders[["order_id", "order_date", "order_status"]],
    on="order_id"
)

order_items["year"] = order_items["order_date"].dt.year

sold_per_year = order_items.groupby("year")["quantity"].sum()

# ===================== RETURNED PER YEAR =====================
returned_orders = orders[orders["order_status"] == "returned"]

returned_items = order_items.merge(
    returned_orders[["order_id"]],
    on="order_id",
    how="inner"
)

returned_per_year = returned_items.groupby("year")["quantity"].sum()

# ===================== RETURN RATE =====================
return_rate = (returned_per_year / sold_per_year).fillna(0)

print(return_rate)

# ===================== PLOT =====================
plt.figure()
plt.plot(return_rate)
plt.title("Return Rate Over Time")
plt.xlabel("Year")
plt.ylabel("Return Rate")
plt.grid()
plt.show()

"""TH3: Tần suất mua giảm (repeat ↓)"""

import pandas as pd
import matplotlib.pyplot as plt

orders["order_date"] = pd.to_datetime(orders["order_date"])

# bỏ cancelled
filtered_orders = orders[orders["order_status"] != "cancelled"]

monthly_stats = filtered_orders.groupby(
    pd.Grouper(key="order_date", freq="ME")
).agg(
    total_orders=("order_id", "nunique"),
    active_customers=("customer_id", "nunique")
)

monthly_stats["orders_per_customer"] = (
    monthly_stats["total_orders"] / monthly_stats["active_customers"]
)

plt.plot(monthly_stats.index, monthly_stats["orders_per_customer"])
plt.title("Orders per Customer Over Time (exclude cancelled)")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

orders["order_date"] = pd.to_datetime(orders["order_date"])
payments = pd.read_csv("Data/payments.csv")

# IMPORTANT: LEFT JOIN để giữ full orders
df = orders.merge(payments, on="order_id", how="left")

monthly = df.groupby(
    pd.Grouper(key="order_date", freq="ME")
).agg(
    orders=("order_id", "nunique"),
    revenue=("payment_value", "sum"),
    avg_payment=("payment_value", "mean")
)

# AOV = revenue / orders (chuẩn hơn mean)
monthly["aov"] = monthly["revenue"] / monthly["orders"]

plt.plot(monthly.index, monthly["orders"], label="Orders")
plt.plot(monthly.index, monthly["aov"], label="AOV")

plt.legend()
plt.title("Orders vs AOV Over Time")
plt.show()

"""**3. Tại sao Street wear doanh thu cao, giá trung bình cao nhất nhưng lợi nhuận thấp?**

Discount quá nhiều?
"""

import pandas as pd

order_items = pd.read_csv("Data/order_items.csv")
products = pd.read_csv("Data/products.csv")

df = order_items.merge(products, on="product_id", how="left")

# Gross revenue
df["gross_revenue"] = df["quantity"] * df["unit_price"]

# Net revenue (quan trọng hơn)
df["net_revenue"] = df["gross_revenue"] - df["discount_amount"].fillna(0)

discount_analysis = df.groupby("category").agg(
    gross_revenue=("gross_revenue", "sum"),
    discount_amount=("discount_amount", "sum"),
    net_revenue=("net_revenue", "sum")
)

discount_analysis["discount_rate"] = (
    discount_analysis["discount_amount"] / discount_analysis["gross_revenue"]
)

print(discount_analysis)

"""Tỷ suất lợi nhuận của các danh mục sản phẩm"""

# cost
df["cost"] = df["quantity"] * df["cogs"].fillna(0)

# profit dùng net revenue (chuẩn hơn)
df["profit"] = df["net_revenue"] - df["cost"]

margin_analysis = df.groupby("category").agg(
    net_revenue=("net_revenue", "sum"),
    profit=("profit", "sum")
)

margin_analysis["margin_pct"] = (
    margin_analysis["profit"] / margin_analysis["net_revenue"]
)

print(margin_analysis)

"""Tính mức độ đội giá của các danh mục để xem chính sách giá có đồng đều không?"""

price_cogs = products.copy()

price_cogs["markup"] = (
    price_cogs["price"] - price_cogs["cogs"]
) / price_cogs["price"]

category_markup = price_cogs.groupby("category").agg(
    avg_price=("price", "mean"),
    avg_cogs=("cogs", "mean"),
    avg_markup=("markup", "mean")
)

print(category_markup)

"""Có phải một số sản phẩm chiếm phần lớn doanh thu nhưng margin thấp không?"""

import pandas as pd

order_items = pd.read_csv("Data/order_items.csv")
products = pd.read_csv("Data/products.csv")

df = order_items.merge(products, on="product_id", how="left")

# Gross revenue
df["revenue"] = df["quantity"] * df["unit_price"]

# Cost
df["cost"] = df["quantity"] * df["cogs"].fillna(0)

# Profit (consistent business logic)
df["profit"] = df["revenue"] - df["cost"] - df["discount_amount"].fillna(0)

# Filter Streetwear
sw = df[df["category"] == "Streetwear"]

# Aggregate
product_perf = sw.groupby("product_id").agg(
    revenue=("revenue", "sum"),
    profit=("profit", "sum")
).reset_index()

# Safe margin calculation
product_perf["margin_pct"] = product_perf["profit"] / product_perf["revenue"].replace(0, pd.NA)

# Top products
top_products = product_perf.sort_values("revenue", ascending=False).head(10)

print(top_products)

"""Margin thấp vì cost quá cao? hay giá bán không đủ cao?"""

# chỉ lấy streetwear
sw = df[df["category"] == "Streetwear"]

product_cost = sw.groupby("product_id").agg({
    "revenue": "sum",
    "quantity": "sum",
    "cogs": "mean"
}).reset_index()

product_cost["cost_ratio"] = (product_cost["cogs"] * product_cost["quantity"]) / product_cost["revenue"]

print(product_cost.sort_values("cost_ratio", ascending=False).head(10))

"""Có phải đang bán giá thấp để kéo volume?"""

product_price = sw.groupby("product_id").agg({
    "unit_price": "mean",
    "revenue": "sum",
    "profit": "sum"
}).reset_index()

product_price["margin"] = product_price["profit"] / product_price["revenue"]

print(product_price.sort_values("revenue", ascending=False).head(10))

"""**4. Tất cả segment đều có stockout ~66% - 68%, overstock ~67% - 79% → Hệ thống tồn kho đang mất cân bằng nghiêm trọng trên toàn bộ danh mục → Doanh nghiệp phân bổ tồn kho không hiệu quả giữa các sản phẩm hoặc khu vực. Mất cân bằng này đến từ đâu? Ảnh hưởng thế nào?**

Xem cung có match cầu không?
"""

import pandas as pd
import matplotlib.pyplot as plt

inventory = pd.read_csv("Data/inventory.csv")

monthly = inventory.groupby(["year", "month"]).agg({
    "units_sold": "sum",
    "units_received": "sum"
}).reset_index()

# tạo trục thời gian
monthly["time"] = monthly["year"].astype(str) + "-" + monthly["month"].astype(str)

plt.figure(figsize=(10,5))
plt.plot(monthly["time"], monthly["units_sold"], label="Demand (Sold)")
plt.plot(monthly["time"], monthly["units_received"], label="Supply (Received)")
plt.xticks(rotation=45)
plt.legend()
plt.title("Demand vs Supply Over Time")
plt.show()

"""Có phải sản phẩm bán chạy bị thiếu, sản phẩm bán chậm bị dư?"""

product = inventory.groupby("product_id").agg({
    "units_sold": "sum",
    "stockout_flag": "mean",
    "overstock_flag": "mean"
}).reset_index()

# xem phân bố
print(product.describe())

plt.figure(figsize=(6,5))

plt.scatter(
    product["units_sold"],
    product["stockout_flag"],
    c=product["overstock_flag"],  # màu = overstock
    alpha=0.4
)

plt.colorbar(label="Overstock Rate")

plt.xlabel("Units Sold")
plt.ylabel("Stockout Rate")
plt.title("Sự lệch pha giữa nhu cầu thực tế và tình trạng tồn kho")
low = product.nsmallest(20, "units_sold")
high = product.nlargest(20, "units_sold")

plt.scatter(product["units_sold"], product["stockout_flag"], c=product["overstock_flag"], alpha=0.3)

plt.scatter(low["units_sold"], low["stockout_flag"], color="red", label="Low demand")
plt.scatter(high["units_sold"], high["stockout_flag"], color="blue", label="High demand")

plt.legend()

plt.show()

"""Có phải segment nào bị phân bổ sai không?"""

segment = inventory.groupby("segment").agg({
    "units_sold": "sum",
    "stock_on_hand": "sum",
    "stockout_flag": "mean",
    "overstock_flag": "mean"
}).reset_index()

print(segment)

segment.set_index("segment")[[
    "stockout_flag", "overstock_flag"
]].plot(kind="bar")

plt.title("Stockout vs Overstock by Segment")
plt.ylabel("Rate")
plt.show()

"""Có phải nhập hàng không kịp?"""

inventory["month_key"] = inventory["year"].astype(str) + "-" + inventory["month"].astype(str)

delay = inventory.groupby("month_key").agg({
    "units_sold": "sum",
    "units_received": "sum"
}).reset_index()

delay["gap"] = delay["units_received"] - delay["units_sold"]

print(delay.tail())

"""Hàng có được bán hết không?"""

eff = inventory.groupby("product_id").agg({
    "sell_through_rate": "mean",
    "stockout_flag": "mean",
    "overstock_flag": "mean"
}).reset_index()

plt.figure()
plt.scatter(eff["sell_through_rate"], eff["overstock_flag"])
plt.xlabel("Sell-through")
plt.ylabel("Overstock")
plt.title("Efficiency vs Overstock")
plt.show()

"""**Tổng quan doanh thu, lợi nhuận và số đơn hàng qua các năm (2012-2022)**"""

# Biểu đồ doanh thu, lợi nhuận và tổng số đơn theo năm
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# ===================== ĐỌC DỮ LIỆU =====================
sales = pd.read_csv("Data/sales.csv")
orders = pd.read_csv("Data/orders.csv")

# Tạo bảng tổng hợp theo năm
sales['Date'] = pd.to_datetime(sales['Date'])
sales['year'] = sales['Date'].dt.year
yearly = sales.groupby('year').agg(
    Revenue=('Revenue', 'sum'),
    COGS=('COGS', 'sum')
).reset_index()
yearly['Profit'] = yearly['Revenue'] - yearly['COGS']

# Tổng số đơn hàng theo năm
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders['year'] = orders['order_date'].dt.year
yearly_orders = orders.groupby('year')['order_id'].nunique().reset_index(name='Orders')

# Ghép
df = yearly.merge(yearly_orders, on='year', how='left')

# Vẽ 3 trục (doanh thu, lợi nhuận, số đơn) - dùng dual-axis cho 2 đường và 1 cột?
# Cách tốt: vẽ 2 biểu đồ riêng biệt hoặc 1 biểu đồ với 2 trục Y và cột cho số đơn.
fig, ax1 = plt.subplots(figsize=(12,6))

# Cột: Số đơn
ax1.bar(df['year'], df['Orders'], color='lightblue', alpha=0.7, label='Orders')
ax1.set_xlabel('Năm')
ax1.set_ylabel('Số đơn', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')

# Đường: Doanh thu và Lợi nhuận trên trục phụ
ax2 = ax1.twinx()
ax2.plot(df['year'], df['Revenue'], color='darkgreen', marker='o', linewidth=2, label='Revenue')
ax2.plot(df['year'], df['Profit'], color='crimson', marker='s', linewidth=2, linestyle='--', label='Profit')
ax2.set_ylabel('Doanh thu & Lợi nhuận', color='black')
ax2.tick_params(axis='y')

# Ghi chú và hiển thị
fig.suptitle('Doanh thu, Lợi nhuận và Số đơn hàng theo năm (2012-2022)', fontsize=14)
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.9))
plt.grid(True, axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Xuất bảng số liệu
print(df[['year', 'Revenue', 'Profit', 'Orders']].round(0).to_string(index=False))

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

customers = pd.read_csv("Data/customers.csv")
orders = pd.read_csv("Data/orders.csv")

# Xử lý ngày tháng
customers['signup_date'] = pd.to_datetime(customers['signup_date'])
orders['order_date'] = pd.to_datetime(orders['order_date'])

# 1. Khách hàng mới theo năm (dựa trên signup_date)
customers['signup_year'] = customers['signup_date'].dt.year
new_customers_by_year = customers.groupby('signup_year').size().reset_index(name='new_customers')

# 2. Tỷ lệ giữ chân (mua lại sau năm đầu)
first_purchase = orders.groupby('customer_id')['order_date'].min().dt.year.reset_index()
first_purchase.columns = ['customer_id', 'first_year']
repeat_counts = []
for year in range(2012, 2022):  # chỉ tính đến 2021 để có cơ hội mua lại
    cohort = first_purchase[first_purchase['first_year'] == year]['customer_id'].unique()
    later_orders = orders[orders['order_date'].dt.year > year]['customer_id'].unique()
    retained = len(set(cohort) & set(later_orders))
    retention_rate = retained / len(cohort) * 100 if len(cohort) > 0 else 0
    repeat_counts.append({'year': year, 'retention_rate': retention_rate})
retention_df = pd.DataFrame(repeat_counts)

# Vẽ biểu đồ kết hợp
fig, ax1 = plt.subplots(figsize=(12,6))
ax1.bar(new_customers_by_year['signup_year'], new_customers_by_year['new_customers'],
        color='steelblue', alpha=0.7, label='Khách hàng mới (đăng ký)')
ax1.set_xlabel('Năm', fontsize=12)
ax1.set_ylabel('Số lượng khách đăng ký', color='blue', fontsize=12)
ax1.tick_params(axis='y', labelcolor='blue')

ax2 = ax1.twinx()
ax2.plot(retention_df['year'], retention_df['retention_rate'],
        color='crimson', marker='o', linewidth=2, label='Tỷ lệ giữ chân (mua lại sau năm đầu)')
ax2.set_ylabel('Tỷ lệ giữ chân (%)', color='crimson', fontsize=12)
ax2.tick_params(axis='y', labelcolor='crimson')

plt.title('Khách hàng mới (theo đăng ký) và Tỷ lệ giữ chân theo năm', fontsize=14)
fig.legend(loc='upper left', bbox_to_anchor=(0.1,0.9))
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# In kết quả ra console (tùy chọn)
print("\nKhách hàng mới theo năm (đăng ký):")
print(new_customers_by_year)
print("\nTỷ lệ giữ chân (có mua lại sau năm đầu):")
print(retention_df)

"""**5. Discount có làm giảm doanh thu?**"""

import pandas as pd
import matplotlib.pyplot as plt

# ===================== ĐỌC DỮ LIỆU =====================
products = pd.read_csv("Data/products.csv")
order_items = pd.read_csv("Data/order_items.csv")

# ===================== XỬ LÝ TÍNH TOÁN =====================
order_items_with_price = order_items.merge(products[['product_id', 'cogs']], on='product_id')
order_items_with_price['revenue'] = order_items_with_price['quantity'] * order_items_with_price['unit_price']
order_items_with_price['cogs_total'] = order_items_with_price['quantity'] * order_items_with_price['cogs']
order_items_with_price['gross_profit'] = order_items_with_price['revenue'] - order_items_with_price['cogs_total']
order_items_with_price['margin'] = order_items_with_price['gross_profit'] / order_items_with_price['revenue'] * 100

promo_group = order_items_with_price['promo_id'].notna()
margin_no_promo = order_items_with_price[~promo_group]['margin'].mean()
margin_promo = order_items_with_price[promo_group]['margin'].mean()
revenue_no_promo = order_items_with_price[~promo_group]['revenue'].sum()
revenue_promo = order_items_with_price[promo_group]['revenue'].sum()

# ===================== VẼ BIỂU ĐỒ =====================
fig, ax = plt.subplots(figsize=(8,5))
categories = ['Không promo', 'Có promo']
margins = [margin_no_promo, margin_promo]
bars = ax.bar(categories, margins, color=['steelblue', 'salmon'])
ax.set_ylabel('Gross Margin (%)')
ax.set_title('Biên lợi nhuận gộp: Đơn hàng có khuyến mãi vs không có')
for i, (bar, margin) in enumerate(zip(bars, margins)):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height()+0.5, f"{margin:.2f}%", ha='center')
ax.text(0, margin_no_promo-3, f"Doanh thu: {revenue_no_promo/1e9:.1f} tỷ", ha='center')
ax.text(1, margin_promo-1, f"Doanh thu: {revenue_promo/1e9:.1f} tỷ", ha='center')
plt.tight_layout()
plt.show()

print(f"Margin không promo: {margin_no_promo:.2f}%")
print(f"Margin có promo: {margin_promo:.2f}%")
print(f"Doanh thu không promo: {revenue_no_promo:.1f}")
print(f"Doanh thu có promo: {revenue_promo:.1f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings('ignore')

# ============================================
# CẤU HÌNH HIỂN THỊ
# ============================================
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor': 'white',
    'axes.edgecolor': '#CCCCCC',
    'axes.linewidth': 0.8,
    'axes.grid': True,
    'grid.color': '#EEEEEE',
    'grid.linewidth': 0.6,
    'xtick.color': '#555555',
    'ytick.color': '#555555',
    'text.color': '#222222',
    'font.family': 'DejaVu Sans',
    'font.size': 10,
    'axes.titlesize': 12,
    'axes.titleweight': 'bold',
    'axes.labelsize': 10,
})

BLUE = '#2E86AB'
GRAY = '#AAAAAA'
RED = '#C0392B'
DARK = '#222222'

# ============================================
# ĐỌC DỮ LIỆU
# ============================================
# Master
products = pd.read_csv('/content/Data/products.csv')
customers = pd.read_csv('/content/Data/customers.csv')
promotions = pd.read_csv('/content/Data/promotions.csv')
geography = pd.read_csv('/content/Data/geography.csv')

# Transaction
orders = pd.read_csv('/content/Data/orders.csv')
order_items = pd.read_csv('/content/Data/order_items.csv')
payments = pd.read_csv('/content/Data/payments.csv')
shipments = pd.read_csv('/content/Data/shipments.csv')
returns = pd.read_csv('/content/Data/returns.csv')
reviews = pd.read_csv('/content/Data/reviews.csv')

# Analytical
sales = pd.read_csv('/content/Data/sales.csv')

# Operational
inventory = pd.read_csv('/content/Data/inventory.csv')
web_traffic = pd.read_csv('/content/Data/web_traffic.csv')

# Convert datetime
orders['order_date'] = pd.to_datetime(orders['order_date'])
returns['return_date'] = pd.to_datetime(returns['return_date'])
reviews['review_date'] = pd.to_datetime(reviews['review_date'])
shipments['ship_date'] = pd.to_datetime(shipments['ship_date'])
shipments['delivery_date'] = pd.to_datetime(shipments['delivery_date'])
inventory['snapshot_date'] = pd.to_datetime(inventory['snapshot_date'])
web_traffic['date'] = pd.to_datetime(web_traffic['date'])
sales['Date'] = pd.to_datetime(sales['Date'])

# ============================================
# CHART 1: Doanh thu theo tháng vs Tỷ lệ khuyến mãi
# ============================================
oi_full = (
    order_items
    .merge(orders[['order_id', 'order_date']], on='order_id')
    .merge(products[['product_id', 'segment', 'category', 'price', 'cogs']], on='product_id')
)
oi_full['order_date'] = pd.to_datetime(oi_full['order_date'])
oi_full['month'] = oi_full['order_date'].dt.to_period('M').dt.to_timestamp()
oi_full['revenue'] = oi_full['unit_price'] * oi_full['quantity']
oi_full['cost'] = oi_full['cogs'] * oi_full['quantity']
oi_full['profit'] = oi_full['revenue'] - oi_full['cost'] - oi_full['discount_amount']
oi_full['has_promo'] = oi_full['promo_id'].notna()

monthly_rev = oi_full.groupby('month').agg(
    revenue=('revenue', 'sum'),
    promo_rate=('has_promo', 'mean')
).reset_index()

fig, ax1 = plt.subplots(figsize=(13, 5))
ax1.plot(monthly_rev['month'], monthly_rev['revenue'] / 1e9, color=BLUE, linewidth=1.5, label='Revenue (tỷ VND)')
ax1.set_ylabel('Revenue (tỷ VND)', color=BLUE)
ax1.tick_params(axis='y', labelcolor=BLUE)
ax1.set_xlabel('Month')

ax2 = ax1.twinx()
ax2.fill_between(monthly_rev['month'], monthly_rev['promo_rate'] * 100, alpha=0.25, color=RED, label='Promo Rate (%)')
ax2.plot(monthly_rev['month'], monthly_rev['promo_rate'] * 100, color=RED, linewidth=0.8, alpha=0.7)
ax2.set_ylabel('Promo Rate (%)', color=RED)
ax2.tick_params(axis='y', labelcolor=RED)

ax1.set_title('Monthly Revenue vs Promotion Rate')
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper right', fontsize=9)
plt.tight_layout()
plt.savefig('chart9_revenue_promo.png', dpi=150)
plt.show()

# ============================================
# CHART 2: Tỷ lệ lợi nhuận theo năm (Profit Margin)
# ============================================
sales['Year'] = sales['Date'].dt.year
yearly_profit = sales.groupby('Year').agg(
    total_revenue=('Revenue', 'sum'),
    total_cogs=('COGS', 'sum')
).reset_index()
yearly_profit['profit'] = yearly_profit['total_revenue'] - yearly_profit['total_cogs']
yearly_profit['profit_margin'] = (yearly_profit['profit'] / yearly_profit['total_revenue']) * 100
yearly_profit = yearly_profit[(yearly_profit['Year'] >= 2012) & (yearly_profit['Year'] <= 2022)]

fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(yearly_profit['Year'], yearly_profit['profit_margin'], marker='o', linewidth=2, markersize=8, color=BLUE)
ax.axhline(y=0, color='red', linestyle='--', linewidth=1, alpha=0.7)
for _, row in yearly_profit.iterrows():
    ax.annotate(f"{row['profit_margin']:.1f}%", (row['Year'], row['profit_margin']),
                textcoords='offset points', xytext=(0, 10), ha='center', fontsize=9)
ax.set_xlabel('Năm')
ax.set_ylabel('Profit Margin (%)')
ax.set_title('Tỷ lệ lợi nhuận theo năm')
ax.set_xticks(yearly_profit['Year'])
ax.grid(True, alpha=0.3)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.show()

# ============================================
# BẢNG 1: Ăn mòn lợi nhuận do khuyến mãi
# ============================================
# Chuẩn bị dữ liệu
df_detailed = order_items.merge(products[['product_id', 'category', 'cogs']], on='product_id', how='left')
df_detailed = df_detailed.merge(promotions[['promo_id', 'promo_type', 'discount_value']], on='promo_id', how='left')
df_detailed['gross_revenue'] = df_detailed['quantity'] * df_detailed['unit_price']
df_detailed['total_cogs'] = df_detailed['quantity'] * df_detailed['cogs']
df_detailed['real_profit'] = df_detailed['gross_revenue'] - df_detailed['total_cogs']
df_detailed['profit_per_item'] = df_detailed['real_profit'] / df_detailed['quantity']
df_detailed['has_promo'] = df_detailed['promo_id'].notna()

promo_comparison = df_detailed.groupby(['category', 'has_promo']).agg(
    avg_profit_per_item=('profit_per_item', 'mean'),
    total_items=('quantity', 'sum')
).reset_index()

pivot_promo = promo_comparison.pivot_table(index='category', columns='has_promo', values='avg_profit_per_item').reset_index()
pivot_promo.columns = ['category', 'non_promo_profit', 'promo_profit']
pivot_promo['profit_erosion'] = pivot_promo['non_promo_profit'] - pivot_promo['promo_profit']
pivot_promo['erosion_pct'] = (pivot_promo['profit_erosion'] / pivot_promo['non_promo_profit']) * 100

print("\n" + "=" * 80)
print("BẢNG 1: ĂN MÒN LỢI NHUẬN DO KHUYẾN MÃI")
print("=" * 80)
print(pivot_promo.to_string(index=False))

# ============================================
# BẢNG 2: Markup Ratio theo segment
# ============================================
df_detailed_seg = order_items.merge(products[['product_id', 'segment', 'cogs']], on='product_id', how='left')
df_detailed_seg['markup_ratio'] = df_detailed_seg['unit_price'] / df_detailed_seg['cogs']
markup_by_segment = df_detailed_seg.groupby('segment')['markup_ratio'].agg(['mean', 'median', 'min', 'max']).reset_index()

print("\n" + "=" * 80)
print("BẢNG 2: MARKUP RATIO THEO SEGMENT")
print("=" * 80)
print(markup_by_segment.sort_values(by='mean', ascending=False).to_string(index=False))

# ============================================
# CHART 3: Markup Ratio by Segment (Bar chart)
# ============================================
markup = markup_by_segment.sort_values('mean', ascending=False)
fig, ax = plt.subplots(figsize=(8, 4))
colors_bar = [RED if m < 1.2 else BLUE for m in markup['mean']]
bars = ax.bar(markup['segment'], markup['mean'], color=colors_bar, width=0.55)
ax.axhline(1.0, color=DARK, linewidth=1.0, linestyle='--', label='Breakeven (1x)')
ax.axhline(markup['mean'].mean(), color=GRAY, linewidth=1.0, linestyle=':', label=f"Mean ({markup['mean'].mean():.3f}x)")
for bar, val in zip(bars, markup['mean']):
    ax.text(bar.get_x() + bar.get_width() / 2, val + 0.003, f'{val:.3f}x', ha='center', fontsize=9)
ax.set_title('Markup Ratio by Segment')
ax.set_ylabel('Markup Ratio')
ax.set_ylim(0, markup['mean'].max() * 1.15)
ax.legend(fontsize=9)
ax.grid(axis='y')
plt.xticks(rotation=15, ha='right')
plt.tight_layout()
plt.savefig('chart13_markup.png', dpi=150)
plt.show()

# ============================================
# BẢNG 3: PHÂN BỔ VỐN (INVENTORY vs PROFIT CONTRIBUTION)
# ============================================
segment_qty = df_detailed_seg.groupby('segment')['quantity'].sum().reset_index()
segment_qty.columns = ['segment', 'total_quantity']
segment_qty['inv_share'] = segment_qty['total_quantity'] / segment_qty['total_quantity'].sum() * 100

# TÍNH LẠI PROFIT THEO SEGMENT TỪ df_detailed_seg
df_detailed_seg['gross_revenue'] = df_detailed_seg['quantity'] * df_detailed_seg['unit_price']
df_detailed_seg['total_cogs'] = df_detailed_seg['quantity'] * df_detailed_seg['cogs']
df_detailed_seg['real_profit'] = df_detailed_seg['gross_revenue'] - df_detailed_seg['total_cogs']

total_profit_seg = df_detailed_seg['real_profit'].sum()
profit_contribution_seg = df_detailed_seg.groupby('segment')['real_profit'].sum().reset_index()
profit_contribution_seg.columns = ['segment', 'total_profit']
profit_contribution_seg['profit_share'] = profit_contribution_seg['total_profit'] / total_profit_seg * 100

allocation_analysis_seg = segment_qty.merge(profit_contribution_seg, on='segment')
allocation_analysis_seg['allocation_gap'] = allocation_analysis_seg['inv_share'] - allocation_analysis_seg['profit_share']
allocation_analysis_seg = allocation_analysis_seg.sort_values('allocation_gap', ascending=False)

print("\n" + "=" * 80)
print("BẢNG 3: PHÂN BỔ VỐN (INVENTORY) vs ĐÓNG GÓP LỢI NHUẬN (THEO SEGMENT)")
print("=" * 80)
print(allocation_analysis_seg[['segment', 'inv_share', 'profit_share', 'allocation_gap']].to_string(index=False))